//Class generated by running the test and copy and pasting the resulting skeleton boiler plate code (and fixing the namespace)
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using System;
using TechTalk.SpecFlow;

namespace uk.co.edgewords.nfocus6specflow.StepDefinitions
{
    [Binding] //This annotation tells Specflow this file contains steps. The name of the file or it's location is not important.
    public class StepDefinitions
    {
        
        IWebDriver driver; //Field accessible to all methods in this class to share driver

        //Not important now, but ScenarioContext can be used to share data (e.g. a WebDriver) across methods, /and/ across step definition classes
        private readonly ScenarioContext _scenarioContext;
        public StepDefinitions(ScenarioContext scenarioContext)
        {
            _scenarioContext = scenarioContext;
        }


        [Given(@"I am on the Google homepage")]
        public void GivenIAmOnTheGoogleHomepage()
        {
            //Skeleton code will throw a Pending exception when initially generated
            //This is essentially your "ToDo": complete the code that does the action specified in the Feature file.
            //_scenarioContext.Pending();
            driver = new EdgeDriver();
            driver.Url = "https://www.google.co.uk";
            //Also need to accept cookies. Not directly specified in the Feature file, but a "technical implied" detail we can handle on the automation side.
            driver.FindElement(By.CssSelector("#L2AGLb")).Click();
        }

        [When(@"I search for '(.*)'")] //RegEx captures a paramitersied value
        public void WhenISearchForEdgewords(string searchTerm) //ANd passes the captured value to the method to use
        {
            driver.FindElement(By.CssSelector("textarea[aria-label=Search]")).SendKeys(searchTerm + Keys.Enter);
        }

        [Then(@"'(.*)' is the top result")] //Then is a validation/assertion point
        public void ThenEdgewordsIsTheTopResult(string searchResult)
        {
            //Capture a value that can be used to check the previous steps have "worked"
            string topResult = driver.FindElement(By.CssSelector("#search h3:not(div > *)")).Text;
            //Assert on the value
            //Nunit Style
            Assert.That(topResult, Does.Contain(searchResult), searchResult + " is not the top result");
            //FluentAssertion style
            //topResult.Should().Contain(searchResult);
        }

    }
}
